drop table if exists users;

CREATE TABLE if not exists users (
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_name varchar(100) NULL,
	user_email varchar(256) NULL,
	CONSTRAINT users_pk PRIMARY KEY (id),
	CONSTRAINT users_unique UNIQUE (user_email)
);