drop table if exists view_statistics;

create table if not exists view_statistics (
    id int8 generated BY DEFAULT AS IDENTITY NOT NULL,
    app varchar(1000) not null,
    uri varchar(1000) not null,
    ip varchar(15) not null,
    created timestamp without time zone NOT NULL,
    constraint statistics_pk primary key(id)
);